### ISSUE TITLE
Request for a permission 

### ISSUE THREAD

**Issue by DQNEO** [DQNEO/Amazon-S3-Thin#18]
Hi @garu ! 
How are you ?

Now I am writing a book about Git/Github in Japan, which will be published next month.

https://www.amazon.co.jp/dp/4863542178

In this book I am explaining about what OSS/Social Coding is like and how fun it is.
Since this Amazon::S3::thin is my first project where I've got lots of PRs from overseas, I would like to take this as a example of OSS activities.

My request is, can I use a capture image of  your PRs in my book? e.g. this one https://github.com/DQNEO/Amazon-S3-Thin/pull/8

**Comment by garu** [comment]
Hi @DQNEO! Congrats on your book, hope it's a success \o/

Of course you can use that PR in your book. I'm honored :)

Cheers!

**Comment by DQNEO** [comment]
Thanks! I really appreciate it :)
