### ISSUE TITLE
Fails when Config::Tiny is not installed

### ISSUE THREAD

**Issue by andk** [DQNEO/Amazon-S3-Thin#25]
As per subject. Sample fail report: http://www.cpantesters.org/cpan/report/97774041

**Comment by DQNEO** [comment]
Thanks for the report!
Actually I declare it here https://github.com/DQNEO/Amazon-S3-Thin/blob/6e3520a40049f150da6c081c618ab56d027dae45/cpanfile#L17
But not sure why that has no effect... 🤔

**Comment by DQNEO** [comment]
fixed and shipped.
https://metacpan.org/release/DQNEO/Amazon-S3-Thin-0.23

**Comment by DQNEO** [comment]
I think it's solved.
